name: Python CI - BDIX Speed Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies including Xvfb
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install -y xvfb
        pip install -r requirements.txt  # Ensure this file is in your repo
        
    # Step 4: Run with offscreen platform only
    - name: Run speed test script
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        python bdix_speed_test.py
